
ERROR:root:index(5) of Request(bySharableMemory).sqlId is not valid for 10.2.0.5.0
	Values:3,095,991;675,186;0.06;cj0wvnp04g7hm
Traceback (most recent call last):
  File "/home/allonzo/workspace/zenity/parsing/Requests.py", line 158, in _getRequestFromArray
    requestId = values[index]
IndexError: list index out of range
ERROR:root:index(4) of Request(byVersionCount).sqlId is not valid for 10.2.0.5.0
	Values:341;2;b4xsb94tpdnus
Traceback (most recent call last):
  File "/home/allonzo/workspace/zenity/parsing/Requests.py", line 158, in _getRequestFromArray
    requestId = values[index]
IndexError: list index out of range
